(()=>{
 const keys=['outputTitle','outputDevice','outputApp','outputSystem','outputHint','outputChanging','outputChanged','ERR_AUDIO_DEVICE','latencyHint','ERR_4K_RESTART'];
 const values={
 pl:['Głośniki i wyjście audio','Wybierz głośnik (★ domyślny Windows)','Przełącz dźwięk aplikacji','Przełącz dźwięk Windows','Działa podczas live. Pierwszy przycisk dotyczy udostępnianego okna z dźwiękiem; drugi całego Windows. Po live przywracamy wcześniejsze wyjścia, zachowując późniejsze zmiany dokonane w Windows. Przy całym ekranie przechwytywanie jest odświeżane.','Przełączam wyjście…','Wyjście przełączone.','Nie udało się zmienić wyjścia audio. Odśwież listę i sprawdź, czy urządzenie jest podłączone.','Mniejsze opóźnienie: rozpocznij nowy live w 720p lub 1080p — YouTube użyje trybu ultra-low. 1440p używa low, 4K normalnego opóźnienia. VRChat może dodawać własny bufor; aplikacja nie steruje odtwarzaczem świata. Zmiana okna może spowodować krótkie buforowanie.','Ta rozdzielczość wymaga nowego live z powodu wybranego trybu opóźnienia YouTube.'],
 en:['Speakers and audio output','Choose speaker (★ Windows default)','Switch app audio','Switch Windows audio','Available during live. The first button affects the shared window with audio; the second affects Windows. Previous outputs are restored after live, preserving later changes made in Windows. Full-screen capture is refreshed.','Switching output…','Output switched.','Could not change audio output. Refresh the list and check the device connection.','For lower delay, start a new 720p or 1080p live: YouTube uses ultra-low latency. 1440p uses low and 4K normal latency. VRChat may add its own buffer; this app cannot control the world player. Source changes may briefly buffer.','This resolution needs a new live because of the YouTube latency mode.'],
 ru:['Динамики и аудиовыход','Выберите динамик (★ основной Windows)','Переключить звук приложения','Переключить звук Windows','Во время эфира: первая кнопка меняет выход окна со звуком, вторая — Windows. После эфира прежние выходы восстанавливаются с сохранением последующих изменений в Windows. Захват всего экрана обновляется.','Переключение выхода…','Выход переключён.','Не удалось изменить аудиовыход. Обновите список и проверьте подключение устройства.','Для меньшей задержки начните новый эфир в 720p или 1080p: ultra-low. 1440p использует low, 4K — normal. VRChat может добавлять буфер, которым приложение не управляет. Смена окна может вызвать короткую паузу.','Для этого разрешения нужен новый эфир из-за режима задержки YouTube.'],
 ja:['スピーカーと音声出力','スピーカーを選択（★ Windows既定）','アプリの音声を切り替え','Windowsの音声を切り替え','配信中に使用できます。最初のボタンは音声付き共有ウィンドウ、次はWindows全体が対象です。終了後に元の出力を復元しますが、後からWindowsで変更した設定は保持します。画面全体の共有は更新されます。','出力を切り替え中…','出力を切り替えました。','出力を変更できません。リストを更新し、機器の接続を確認してください。','遅延を減らすには720pまたは1080pで新しい配信を開始します（超低遅延）。1440pは低遅延、4Kは通常遅延です。VRChat独自のバッファは操作できません。共有元の変更時には一時停止する場合があります。','YouTubeの遅延モードにより、この解像度には新しい配信が必要です。'],
 de:['Lautsprecher und Audioausgang','Lautsprecher wählen (★ Windows-Standard)','App-Audio umschalten','Windows-Audio umschalten','Während des Streams: Die erste Taste betrifft das geteilte Fenster mit Ton, die zweite Windows. Danach werden vorherige Ausgänge wiederhergestellt; spätere Windows-Änderungen bleiben erhalten. Bildschirmaufnahme wird neu verbunden.','Ausgang wird gewechselt…','Ausgang gewechselt.','Audioausgang konnte nicht geändert werden. Liste aktualisieren und Verbindung prüfen.','Für weniger Verzögerung einen neuen Stream in 720p oder 1080p starten: Ultra-Low. 1440p nutzt Low, 4K Normal. Der VRChat-Puffer kann nicht von dieser App gesteuert werden. Quellenwechsel können kurz puffern.','Diese Auflösung benötigt wegen des YouTube-Latenzmodus einen neuen Stream.'],
 fr:['Haut-parleurs et sortie audio','Choisir une sortie (★ défaut Windows)','Changer le son de l’application','Changer le son de Windows','Pendant le direct : le premier bouton concerne la fenêtre partagée avec audio, le second Windows. Les sorties précédentes sont restaurées après le direct, en conservant les changements ultérieurs dans Windows. La capture plein écran est actualisée.','Changement de sortie…','Sortie modifiée.','Impossible de changer la sortie. Actualisez la liste et vérifiez la connexion.','Pour réduire le délai, démarrez un nouveau direct en 720p ou 1080p : ultra-faible latence. 1440p utilise faible et 4K normale. Le tampon VRChat échappe au contrôle de cette application. Changer de source peut provoquer une courte pause.','Cette résolution nécessite un nouveau direct en raison du mode de latence YouTube.'],
 ko:['스피커 및 오디오 출력','스피커 선택 (★ Windows 기본값)','앱 오디오 전환','Windows 오디오 전환','방송 중 사용합니다. 첫 버튼은 소리가 있는 공유 창, 두 번째는 Windows 전체에 적용됩니다. 방송 후 이전 출력을 복원하며 이후 Windows에서 변경한 설정은 유지합니다. 전체 화면 캡처는 새로 연결됩니다.','출력 전환 중…','출력이 전환되었습니다.','출력을 변경할 수 없습니다. 목록을 새로 고치고 연결을 확인하세요.','지연을 줄이려면 720p 또는 1080p로 새 방송을 시작하세요(초저지연). 1440p는 저지연, 4K는 일반 지연입니다. VRChat의 자체 버퍼는 이 앱에서 제어할 수 없습니다. 소스 전환 시 잠시 멈출 수 있습니다.','YouTube 지연 모드 때문에 이 해상도는 새 방송이 필요합니다.'],
 zh:['扬声器和音频输出','选择扬声器（★ Windows默认）','切换应用声音','切换Windows声音','直播期间可用。第一个按钮针对带声音的共享窗口，第二个针对整个Windows。结束后恢复原输出，但保留此后在Windows中手动修改的设置。全屏捕获会重新连接。','正在切换输出…','输出已切换。','无法更改输出。请刷新列表并检查设备连接。','要减少延迟，请用720p或1080p开始新直播（超低延迟）。1440p使用低延迟，4K使用正常延迟。VRChat自身的缓冲无法由本应用控制。切换来源可能短暂停顿。','由于YouTube延迟模式，此分辨率需要重新开始直播。']};
 for(const [lang,items] of Object.entries(values)){Object.assign(translations[lang],Object.fromEntries(keys.map((key,i)=>[key,items[i]])));translations[lang].helpAudio+='\n\n'+items[4];translations[lang].helpQuality+='\n\n'+items[8];}
 const labels={pl:['Ustawienia dźwięku','Zastosuj dźwięk','Zastosuj wideo','Ustawienia dźwięku zastosowane.','Opóźnienie transmisji'],en:['Audio settings','Apply audio','Apply video','Audio settings applied.','Stream latency'],ru:['Настройки звука','Применить звук','Применить видео','Настройки звука применены.','Задержка трансляции'],ja:['音声設定','音声を適用','映像を適用','音声設定を適用しました。','配信の遅延'],de:['Audioeinstellungen','Audio anwenden','Video anwenden','Audioeinstellungen angewendet.','Stream-Latenz'],fr:['Réglages audio','Appliquer le son','Appliquer la vidéo','Réglages audio appliqués.','Latence du direct'],ko:['오디오 설정','오디오 적용','영상 적용','오디오 설정이 적용되었습니다.','방송 지연'],zh:['音频设置','应用音频','应用视频','音频设置已应用。','直播延迟']};
 for(const [lang,items] of Object.entries(labels))Object.assign(translations[lang],Object.fromEntries(['audioSettings','applyAudio','applyVideo','audioApplied','latencyTitle'].map((key,i)=>[key,items[i]])));
})();
